apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookorbit-postgres
  namespace: bookorbit
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bookorbit-postgres
  template:
    metadata:
      labels:
        app: bookorbit-postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg18
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bookorbit-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookorbit-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: bookorbit-secrets
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bookorbit-postgres
