apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: jellyfin
spec:
  secretName: jellyfin-tls
  dnsNames:
    - jellyfin.blinde.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
