apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookorbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/BobBlinde/KubeLab.git
    targetRevision: main
    path: manifests/bookorbit

  destination:
    server: https://kubernetes.default.svc
    namespace: bookorbit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
