apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-tls
  namespace: sabnzbd
spec:
  secretName: sabnzbd-tls
  dnsNames:
    - sabnzbd.blinde.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
